In [1]:
import os
import sys
import geopandas as gpd

In [2]:
new_gdf = gpd.read_file('./sorghum/season14_multi_latlon_geno_correction.geojson')
old_gdf = gpd.read_file('./sorghum/season14_multi_latlon_geno_updated.geojson')

In [3]:
old_gdf = old_gdf[['ID', 'geometry']].rename(columns={
    'ID': 'error_ID',
})

In [4]:
gdf = new_gdf.merge(old_gdf, on='geometry')

In [5]:
gdf.loc[gdf['ID'] != gdf['error_ID'], 'mismatch'] = 'error'
gdf.loc[gdf['ID'] == gdf['error_ID'], 'mismatch'] = 'no error'

In [6]:
fb = pd.read_excel('https://data.cyverse.org/dav-anon/iplant/projects/phytooracle/season_14_sorghum_yr_2022/North_gantry_fieldbook_2022_replants.xlsx',
                   sheet_name='Fieldbook_replant')

fb = fb[['year', 'range', 'row', 'plot', 'type', 'rep', 'treatment', 'species', 'accession', 'Entry_ID']]
fb['plot'] = fb['plot'].astype(str)

In [7]:
gdf['plot'] = gdf["ID"]

In [8]:
gdf = fb.merge(gdf, on='plot')

In [9]:
gdf = gpd.GeoDataFrame(gdf)

In [10]:
gdf.to_file('./sorghum/season14_multi_latlon_geno_correction_labeled.geojson', driver="GeoJSON")

In [11]:
gdf

,year,range,row,plot,type,rep,treatment,species,accession,Entry_ID,ID,geometry,error_ID,mismatch
0,2022,55,1,5501,border,NaN,WL,sorghum bicolor,BTx623,Az22-429,5501,"MULTIPOLYGON (((-111.97505 33.07665, -111.9750...",5503,error
1,2022,55,2,5502,border,NaN,WL,sorghum bicolor,BTx623,Az22-429,5502,"MULTIPOLYGON (((-111.97505 33.07665, -111.9750...",5504,error
2,2022,55,3,5503,border,NaN,WL,sorghum bicolor,BTx623,Az22-429,5503,"MULTIPOLYGON (((-111.97504 33.07665, -111.9750...",5505,error
3,2022,55,4,5504,border,NaN,WL,sorghum bicolor,BTx623,Az22-429,5504,"MULTIPOLYGON (((-111.97503 33.07665, -111.9750...",5506,error
4,2022,55,5,5505,border,NaN,WL,sorghum bicolor,BTx623,Az22-429,5505,"MULTIPOLYGON (((-111.97502 33.07665, -111.9750...",5507,error
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,2022,94,28,9428,border,NaN,WW,sorghum bicolor,BTx623,Az22-429,9428,"MULTIPOLYGON (((-111.97484 33.07806, -111.9748...",9428,no error
1276,2022,94,29,9429,border,NaN,WW,sorghum bicolor,BTx623,Az22-429,9429,"MULTIPOLYGON (((-111.97483 33.07806, -111.9748...",9429,no error
1277,2022,94,30,9430,border,NaN,WW,sorghum bicolor,BTx623,Az22-429,9430,"MULTIPOLYGON (((-111.97482 33.07806, -111.9748...",9430,no error
1278,2022,94,31,9431,border,NaN,WW,sorghum bicolor,BTx623,Az22-429,9431,"MULTIPOLYGON (((-111.97481 33.07806, -111.9748...",9431,no error
1279,2022,94,32,9432,border,NaN,WW,sorghum bicolor,BTx623,Az22-429,9432,"MULTIPOLYGON (((-111.97480 33.07806, -111.9747...",9432,no error